### ISSUE TITLE
Scrapy 2.6 support

### ISSUE THREAD

**Issue by Gallaecio** [scrapinghub/scrapinghub-entrypoint-scrapy#64]
```
Traceback (most recent call last):
  File "/usr/local/bin/shub-image-info", line 8, in <module>
    sys.exit(shub_image_info())
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/crawl.py", line 209, in shub_image_info
    _run_usercode(None, ['scrapy', 'shub_image_info'] + sys.argv[1:],
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/crawl.py", line 148, in _run_usercode
    _run(args, settings)
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/crawl.py", line 103, in _run
    _run_scrapy(args, settings)
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/crawl.py", line 111, in _run_scrapy
    execute(settings=settings)
  File "/usr/local/lib/python3.10/site-packages/scrapy/cmdline.py", line 140, in execute
    cmd.add_options(parser)
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/commands/shub_image_info.py", line 23, in add_options
    parser.add_option("--debug", action="store_true",
AttributeError: 'ArgumentParser' object has no attribute 'add_option'. Did you mean: '_add_action'?
```

Caused by https://github.com/scrapy/scrapy/pull/5374

**Comment by ahmedshahriar** [comment]
Any update on this?

**Comment by elacuesta** [comment]
> Any update on this?

Nothing more to do here, it was fixed by #65 and released as [`v0.13.0`](https://github.com/scrapinghub/scrapinghub-entrypoint-scrapy/releases/tag/v0.13.0)

**Comment by stefan1984** [comment]
Any update on this?

**Comment by Gallaecio** [comment]
Anyone still affected by this at this point is likely not using the latest version of this package.

In Scrapy Cloud, the default Scrapy stack uses and old version of this package (and of Scrapy, etc.). You need to either [upgrade your stack](https://support.zyte.com/support/solutions/articles/22000200402-changing-the-deploy-environment-with-scrapy-cloud-stacks) to `scrapy:2.7` or later, or include `scrapinghub-entrypoint-scrapy>=0.13.0` in your `requirements.txt` file to force its upgrade to the latest version.
