### PR TITLE
Scrapy 2.6 compatibility

### LINKED ISSUE #64: Scrapy 2.6 support
```
Traceback (most recent call last):
  File "/usr/local/bin/shub-image-info", line 8, in <module>
    sys.exit(shub_image_info())
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/crawl.py", line 209, in shub_image_info
    _run_usercode(None, ['scrapy', 'shub_image_info'] + sys.argv[1:],
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/crawl.py", line 148, in _run_usercode
    _run(args, settings)
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/crawl.py", line 103, in _run
    _run_scrapy(args, settings)
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/crawl.py", line 111, in _run_scrapy
    execute(settings=settings)
  File "/usr/local/lib/python3.10/site-packages/scrapy/cmdline.py", line 140, in execute
    cmd.add_options(parser)
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/commands/shub_image_info.py", line 23, in add_options
    parser.add_option("--debug", action="store_true",
AttributeError: 'ArgumentParser' object has no attribute 'add_option'. Did you mean: '_add_action'?
```

Caused by https://github.com/scrapy/scrapy/pull/5374

### PR DESCRIPTION
**Pull request by elacuesta**
Fixes #64

Also:
* migrate CI from Travis to GitHub Actions
* remove py2 support

Python 3.10 support should be possible after https://github.com/scrapinghub/python-scrapinghub/pull/166

### CODE REVIEW

**Review by Gallaecio — APPROVED** [review]
Looks good to me.

I would just remove py10 from tox if you plan to add Python 3.10 support in a separate pull request.

**Comment by elacuesta** [comment]
Good catch, thanks!
